### ISSUE TITLE
Please propagate information about fedora-rawhide testing through a pipeline

### ISSUE THREAD

**Issue by kkaarreell** [fedora-ci/dist-git-pipeline#48]
In https://github.com/fedora-ci/dist-git-pipeline/blob/master/config.json
Rawhide is defined as `distro: fedora-38`. This is a bit unfortunate as it won't let me do rawhide specific
adjustments in my `tmt` test plans.

I wanted to use something like this
```
adjust:
     - when: distro == fedora-rawhide
       environment:
           AVC_CHECK_AUSEARCH_PARAMS: "-se keylime"
       because: "On Rawhide we ignore SELinux AVCs not related to keylime"
```
but it doesn't work since distro is not `fedora-rawhide` but `fedora-38`.
I do not want to use hardcoded Fedora version since it would force me to update this plan once F38 becomes stable.

Therefore, I need iether `distro: fedora-rawhide` (which works in Testing Farm) or at least additional context presenting this information (e.g. `target_branch: rawhide`).
